# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 2m
  tests: true
  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - varcheck

    - goconst
    - goimports
    - gosec
    - misspell
    # - prealloc
    - unconvert
    # - unparam

linters-settings:
  gofmt:
    simplify: true
  goconst:
    min-len: 3 # minimum length of string constant
    min-occurrences: 6 # minimum number of occurrences

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: api/model.*\.go
      linters:
        - misspell

  exclude:
    - composites
