steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us.gcr.io/$PROJECT_ID/rosetta:$COMMIT_SHA',
    '-t', 'us.gcr.io/$PROJECT_ID/rosetta:$TAG_NAME',
    '-t', 'us.gcr.io/$PROJECT_ID/rosetta:latest',
    '--build-arg', 'COMMIT_SHA=$COMMIT_SHA',
    '.',
    ]
  waitFor: ["-"]
images:
- 'us.gcr.io/$PROJECT_ID/rosetta:$COMMIT_SHA'
- 'us.gcr.io/$PROJECT_ID/rosetta:$TAG_NAME'
- 'us.gcr.io/$PROJECT_ID/rosetta:latest'
timeout: 2700s
