steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us.gcr.io/$PROJECT_ID/rosetta:$COMMIT_SHA', '--build-arg', 'COMMIT_SHA=$COMMIT_SHA', '.' ]
  waitFor: ["-"]
images:
- 'us.gcr.io/$PROJECT_ID/rosetta:$COMMIT_SHA'
timeout: 2700s
