/*
 * Rosetta
 *
 * A standard for blockchain interaction
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"os"

	"github.com/celo-org/rosetta/api"
	"github.com/celo-org/rosetta/celo/client"
	"github.com/celo-org/rosetta/internal/config"
	"github.com/ethereum/go-ethereum/log"
	"github.com/ethereum/go-ethereum/rpc"
)

func main() {
	log.Root().SetHandler(log.LvlFilterHandler(log.LvlInfo, log.StreamHandler(os.Stderr, log.TerminalFormat(true))))

	log.Info("Server started")

	// Read Configuration Variables
	config.ReadConfig()

	rpcClient, err := rpc.Dial("https://alfajores-forno.celo-testnet.org/")
	if err != nil {
		log.Crit("Can't connect to node", "err", err)
	}
	celoClient := client.NewCeloClient(rpcClient)

	api.StartHttpServer(celoClient)
}
