/*
 * Rosetta
 *
 * A standard for blockchain interaction
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// ConstructionApiService is a service that implents the logic for the ConstructionApiServicer
// This service should implement the business logic for every endpoint for the ConstructionApi API.
// Include any external packages or services that will be required by this service.
type ConstructionApiService struct {
}

// NewConstructionApiService creates a default api service
func NewConstructionApiService() ConstructionApiServicer {
	return &ConstructionApiService{}
}

// TransactionConstruction - Get Transaction Construction Metadata
func (s *ConstructionApiService) TransactionConstruction(transactionConstructionRequest TransactionConstructionRequest) (interface{}, error) {
	// TODO - update TransactionConstruction with the required logic for this service method.
	return nil, errors.New("service method 'TransactionConstruction' not implemented")
}

// TransactionSubmit - Submit a Signed Transaction
func (s *ConstructionApiService) TransactionSubmit(transactionSubmitRequest TransactionSubmitRequest) (interface{}, error) {
	// TODO - update TransactionSubmit with the required logic for this service method.
	return nil, errors.New("service method 'TransactionSubmit' not implemented")
}
