/*
 * Rosetta
 *
 * A standard for blockchain interaction
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A AccountApiController binds http requests to an api service and writes the service results to the http response
type AccountApiController struct {
	service AccountApiServicer
}

// NewAccountApiController creates a default api controller
func NewAccountApiController(s AccountApiServicer) Router {
	return &AccountApiController{ service: s }
}

// Routes returns all of the api route for the AccountApiController
func (c *AccountApiController) Routes() Routes {
	return Routes{ 
		{
			"AccountBalance",
			strings.ToUpper("Post"),
			"/account/balance",
			c.AccountBalance,
		},
	}
}

// AccountBalance - Get an Account Balance
func (c *AccountApiController) AccountBalance(w http.ResponseWriter, r *http.Request) { 
	accountBalanceRequest := &AccountBalanceRequest{}
	if err := json.NewDecoder(r.Body).Decode(&accountBalanceRequest); err != nil {
		w.WriteHeader(500)
		return
	}
	
	result, err := c.service.AccountBalance(*accountBalanceRequest)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}
