/*
 * Rosetta
 *
 * <h2>Backstory</h2> Writing reliable blockchain integrations is complicated and time-consuming. The process requires careful analysis of the unique aspects of each blockchain and extensive communication with its developers to understand the best strategies to deploy nodes, recognize deposits, broadcast transactions, etc. Even a minor misunderstanding can lead to downtime, or even worse, incorrect fund attribution. Not to mention, this integration must be continuously modified and tested each time a blockchain team releases new software.  Instead of spending time working on their blockchain, project developers spend countless hours answering similar support questions for each team integrating their blockchain. With their questions answered, each integrating team then writes similar code to interface with the blockchain instead of spending their engineering resources adding support for more blockchain projects or working on unique products and applications.  <h2>A Standard for Blockchain Interaction</h2> Rosetta is a new project from Coinbase to standardize the process of deploying and interacting with blockchains. With an explicit specification to adhere to, all parties involved in blockchain development can spend less time figuring out how to integrate with each other and more time working on the novel advances that will push the blockchain ecosystem forward. In practice, this means that any blockchain project that implements the requirements outlined in this specification will enable exchanges, block explorers, and wallets to integrate with much less communication overhead and network-specific work.  <h5>© 2020 Coinbase</h5> 
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// MempoolApiService is a service that implents the logic for the MempoolApiServicer
// This service should implement the business logic for every endpoint for the MempoolApi API. 
// Include any external packages or services that will be required by this service.
type MempoolApiService struct {
}

// NewMempoolApiService creates a default api service
func NewMempoolApiService() MempoolApiServicer {
	return &MempoolApiService{}
}

// Mempool - Get All Mempool Transactions
func (s *MempoolApiService) Mempool(mempoolRequest MempoolRequest) (interface{}, error) {
	// TODO - update Mempool with the required logic for this service method.
	// Add api_mempool_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'Mempool' not implemented")
}

// MempoolTransaction - Get a Mempool Transaction
func (s *MempoolApiService) MempoolTransaction(mempoolTransactionRequest MempoolTransactionRequest) (interface{}, error) {
	// TODO - update MempoolTransaction with the required logic for this service method.
	// Add api_mempool_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'MempoolTransaction' not implemented")
}
