/*
 * Rosetta
 *
 * A standard for blockchain interaction
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// BlockApiService is a service that implents the logic for the BlockApiServicer
// This service should implement the business logic for every endpoint for the BlockApi API.
// Include any external packages or services that will be required by this service.
type BlockApiService struct {
}

// NewBlockApiService creates a default api service
func NewBlockApiService() BlockApiServicer {
	return &BlockApiService{}
}

// Block - Get a Block
func (s *BlockApiService) Block(blockRequest BlockRequest) (interface{}, error) {
	// TODO - update Block with the required logic for this service method.
	return nil, errors.New("service method 'Block' not implemented")
}

// BlockTransaction - Get a Block Transaction
func (s *BlockApiService) BlockTransaction(blockTransactionRequest BlockTransactionRequest) (interface{}, error) {
	// TODO - update BlockTransaction with the required logic for this service method.
	return nil, errors.New("service method 'BlockTransaction' not implemented")
}
