/*
 * Rosetta
 *
 * A standard for blockchain interaction
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AccountIdentifier - The `account_identifier` uniquely identifies an account within a network. 
type AccountIdentifier struct {

	// The `address` may be a cryptographic public key (or some encoding of it) or a provided username. 
	Address string `json:"address"`

	SubAccount SubAccountIdentifier `json:"sub_account,omitempty"`

	// Blockchains that utilize a username model (where the address is not a derivative of a cryptographic public key) should specify the public key(s) owned by the address in metadata. 
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
