/*
 * Rosetta
 *
 * A standard for blockchain interaction
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NetworkStatusRequest struct {

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
