/*
 * Rosetta
 *
 * A standard for blockchain interaction
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TransactionSubmitRequest struct {

	SignedTransaction string `json:"signed_transaction"`
}
