/*
 * Rosetta
 *
 * A standard for blockchain interaction
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"math/big"

	admin "github.com/celo-org/rosetta/celo/client/admin"
	network "github.com/celo-org/rosetta/celo/client/network"
	eth "github.com/ethereum/go-ethereum/ethclient"
	"github.com/ethereum/go-ethereum/rpc"
)

// NetworkApiService is a service that implents the logic for the NetworkApiServicer
// This service should implement the business logic for every endpoint for the NetworkApi API.
// Include any external packages or services that will be required by this service.
type NetworkApiService struct {
	adminClient   *admin.AdminClient
	networkClient *network.NetworkClient
	ethClient     *eth.Client
}

// NewNetworkApiService creates a default api service
func NewNetworkApiService(rpcClient *rpc.Client) NetworkApiServicer {
	return &NetworkApiService{
		adminClient:   admin.NewClient(rpcClient),
		networkClient: network.NewClient(rpcClient),
		ethClient:     eth.NewClient(rpcClient),
	}
}

// NetworkStatus - Get Network Status
func (s *NetworkApiService) NetworkStatus(networkStatusRequest NetworkStatusRequest) (interface{}, error) {
	ctx := context.Background()

	chainId, err := s.networkClient.ChainId(ctx)
	if err != nil {
		return BuildErrorResponse(1, err), nil
	}

	latestHeader, err := s.ethClient.HeaderByNumber(ctx, nil) // nil == latest
	if err != nil {
		return BuildErrorResponse(2, err), nil
	}

	genesisHeader, err := s.ethClient.HeaderByNumber(ctx, big.NewInt(0)) // 0 == genesis
	if err != nil {
		return BuildErrorResponse(3, err), nil
	}

	peersInfo, err := s.adminClient.Peers(ctx)
	if err != nil {
		return BuildErrorResponse(4, err), nil
	}

	response := NetworkStatusResponse{
		NetworkStatus: NetworkStatus{
			NetworkIdentifier: PartialNetworkIdentifier{
				Blockchain: BlockchainName,
				Network:    NetworkNameFromId(chainId),
			},
			NetworkInformation: NetworkInformation{
				CurrentBlockIdentifier: BlockIdentifierFromHeader(latestHeader),
				CurrentBlockTimestamp:  int64(latestHeader.Time),
				GenesisBlockIdentifier: BlockIdentifierFromHeader(genesisHeader),
				Peers:                  PeersFromInfo(peersInfo),
			},
		},
		SubNetworkStatus: []SubNetworkStatus{},
		Version: Version{
			RosettaVersion:    RosettaVersion,
			NodeVersion:       NodeVersion,
			MiddlewareVersion: MiddlewareVersion,
		},
		// TODO: implement
		Options: Options{
			Methods:           []string{},
			OperationStatuses: []OperationStatus{},
			OperationTypes:    []string{},
		},
		Metadata: map[string]interface{}{},
	}
	return response, nil
}
