/*
 * Rosetta
 *
 * A standard for blockchain interaction
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type Peer struct {
	PeerId string `json:"peer_id"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
