/*
 * Rosetta
 *
 * A standard for blockchain interaction
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// BlockIdentifier - The `block_identifier` uniquely identifies a block in a particular network. 
type BlockIdentifier struct {

	Index int64 `json:"index"`

	Hash string `json:"hash"`
}
