/*
 * Rosetta
 *
 * A standard for blockchain interaction
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// SubAccountIdentifier - An account may have state specific to a contract address (ERC-20 token) and/or a stake (delegated balance). The `sub_account_identifier` should specify which state (if applicable) the account instantiation refers to.
type SubAccountIdentifier struct {
	SubAccount string `json:"sub_account"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
