/*
 * Rosetta
 *
 * A standard for blockchain interaction
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// PartialBlockIdentifier - When fetching data by `BlockIdentifier`, it may be possible to only specify the `index` or `hash`. If neither property is specified, it is assumed that the client is making a request at the current block. 
type PartialBlockIdentifier struct {

	Index int64 `json:"index,omitempty"`

	Hash string `json:"hash,omitempty"`
}
