/*
 * Rosetta
 *
 * A standard for blockchain interaction
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// PartialNetworkIdentifier - The `partial_network_identifier` specifies which network a particular object is associated with (exculding the `sub_network_identifier`). This identifier is used exclusively in `/network/status`. 
type PartialNetworkIdentifier struct {

	Blockchain string `json:"blockchain"`

	Network string `json:"network"`
}
