/*
 * Rosetta
 *
 * A standard for blockchain interaction
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type Amount struct {

	// Value of the transaction in atomic units represented as an arbitrary-sized signed integer.  For example, 1 BTC would be represented by a value of 100000000. 
	Value string `json:"value"`

	Currency Currency `json:"currency"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
