/*
 * Rosetta
 *
 * A standard for blockchain interaction
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// TransactionIdentifier - The `transaction_identifier` uniquely identifies a transaction in a particular network and block or in the mempool.
type TransactionIdentifier struct {
	Hash string `json:"hash"`
}
