/*
 * Rosetta
 *
 * A standard for blockchain interaction
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type SubNetworkStatus struct {

	SubNetworkIdentifier SubNetworkIdentifier `json:"sub_network_identifier"`

	NetworkInformation NetworkInformation `json:"network_information"`
}
