/*
 * Rosetta
 *
 * A standard for blockchain interaction
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type TransactionSubmitResponse struct {

	TransactionIdentifier TransactionIdentifier `json:"transaction_identifier"`

	// Network-specific transaction submission status
	Status string `json:"status"`

	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
