name: Celo Rosetta CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: '1.19'

        - name: Install dependencies
          run: make deps
        
        - name: Check licenses 
          run: make check-license

        - name: Linting
          uses: golangci/golangci-lint-action@v7
          with:
            version: v1.50

        - name: Build
          run: make all

        - name: Test
          run: make test
        