name: Docker Build Scan
on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  Build-Scan-Container:
    uses: celo-org/reusable-workflows/.github/workflows/container-cicd-local.yaml@v2.0.1
    with:
      dockerfile: Dockerfile
